GET http://localhost/load

###

GET http://localhost/programs

###

GET http://localhost/workout

###

POST /create HTTP/1.1
HOST: localhost
Content-Type:application/json
Accept:application/json

{
    "email": "1",
    "user": "admin2",
    "pass": "admin"
}

###

POST /login HTTP/1.1
HOST: localhost
Content-Type:application/json
Accept:application/json

{
    "user": "admin",
    "pass": "admin"
}

###

POST /logout HTTP/1.1
HOST: localhost

###

POST /nextworkout HTTP/1.1
HOST: localhost
Content-Type:application/json
Accept:application/json