INSERT INTO all_exercises(name)
VALUES
("Bench Press"),
("Squat"),
("Deadlift"),
("Rack pulls"),
("Wheighted pushups, shoulder wide"),
("Deadlift to knees"),
("Front Squat"),
("Flat Dumbell flyes"),
("Good mornings, standing"),
("Incline Bench Press"),
("Dips"),
("Lunges"),
("Abs"),
("French Press"),
("Good Mornings, seated"),
("Military Press"),
("Hyper Extensions"),
("Triceps"),
("Barbell Rows"),
("Wheighted pushups, wide"),
("Pistol Squats"),
("Chin Ups"),
("Leg Extensions"),
("Competetion Day!"),
("Deficit Deadlift"),
("Dumbbell press");
;